server:
  port: 8080

spring:
  datasource:
    name: test  #数据库名
    url: jdbc:mysql://127.0.0.1:3306/other?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC #url
    username: root  #用户名
    password: root  #密码
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    com.baomidou.mybatisplus.samples: info

prop:
  upload-folder: E:/test/

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.example.other.entity

